from pydantic import BaseModel

class SmurfFeatures(BaseModel):
    income_am: float
    profit_last_am: float
    profit_am: float
    damage_am: float
    damage_inc: float
    crd_lim_rec: float
    credit_use_ic: bool
    gluten_ic: bool
    lactose_ic: bool
    insurance_ic: bool
    spa_ic: bool
    empl_ic: bool
    cab_requests: float
    married_cd: bool
    bar_no: float
    sport_ic: bool
    neighbor_income: float
    age: float
    marketing_permit: bool
    urban_ic: bool
    client_segment: float
    sect_empl: float
    prev_stay: bool
    prev_all_in_stay: bool
    divorce: bool
    fam_adult_size: float
    children_no: float
    tenure_mts: float
    company_ic: bool
    claims_no: float
    claims_am: float
    nights_booked: float
    shop_am: float
    shop_use: bool
    retired: bool
    gold_status: bool
    gender_M: bool
    gender_V: bool
    score_pos: float
    score_neg: float
    tenure_started_in_season: bool
    dining_ic_False: bool
    dining_ic_True: bool
    dining_ic_missing: bool
    presidential_False: bool
    presidential_True: bool
    presidential_missing: bool
    is_return_customer: bool
